name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: TrivyScan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Docker Registry
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
#      run: docker login -u <username> -p <password>
    - name: Scan
      uses: docker://aquasec/trivy
      with:
        args: --no-progress --ignore-unfixed texanraj/webgoat:latest
