name: Scan
on: [push, pull_request]
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Scan
      uses: docker://aquasec/trivy
      with:
        args: --severity CRITICAL --no-progress texanraj/welcomeapp:latest
